# -*- coding: utf-8 -*-
"""Archivos EFC  + 250 Líneas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQR9Ek2hlSZiG1JwckUQXMwxvErJbYnG
"""

import pandas as pd

results = pd.read_csv('eFC_orders_30_Nov - MX.csv')

def revision_csv():
  if len(results) > 250:
    print("El archivo tiene más de 250 líneas en tu csv, necesitas dividir")
    print("Procediendo a la división")
    cantidad_separacion_archivo()
  else:
    print("Puedes mandar tu archivo")

def cantidad_separacion_archivo():
  numero = len(results) / 2
  entero = int(numero)
  apprix_1 = results.iloc[:entero,:]
  apprix_2 = results.iloc[entero:,:]
  print("Tu archivo se dividirá en 2 partes ahora tiene",len(apprix_1),"El primer archivo y ", len(apprix_2),
        "El segundo archivo")
  print("Guardando archivos...")
  save_csv()

def save_csv():
  apprix_1.to_csv('/content/archivo_efc_1_parte.csv', index=False)
  apprix_2.to_csv('/content/archivo_efc_2_parte.csv',index=False)
  print("Los archivos han sido generados :)")
  print("Tu archivo original tenía",len(results),"lineas")

revision_csv()
